### ISSUE TITLE
Dependency Missing: pyfiglet

### ISSUE THREAD

**Issue by guzman109** [sdsc-hpc-training-org/hello_icicle_auth_clients#20]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/guzman109/Documents/hello-icicle/.venv/lib/python3.10/site-packages/TapisCLICICLE/__main__.py", line 3, in <module>
    from TapisCLICICLE.client.cli import CLI
  File "/home/guzman109/Documents/hello-icicle/.venv/lib/python3.10/site-packages/TapisCLICICLE/client/cli.py", line 11, in <module>
    import pyfiglet
ModuleNotFoundError: No module named 'pyfiglet'

**Comment by MalinkyZubr** [comment]
fixed the dependencies in most recent update
